---
title: "Project 1"
author: "Sam Barans, Ely Boidaha,and Charlie Cochrane"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 pdf_document:
     pandoc_args: ["--extract-media", "."]
---


```{r setup, include=TRUE, echo = FALSE}
# Leave this chunk as it is. It sets defaults for subsequent chunks.
# The "echo" option tells Rmarkdown whether or not it should show the code in the chunk.
# Setting echo = TRUE outputs both the code and the results
knitr::opts_chunk$set(echo = TRUE,
                     collapse = TRUE,
                     warning = FALSE, message = FALSE, error = FALSE,
                     fig.align = 'center')
library(tidyverse)
library(lubridate)
```

## Part 1


```{r part 1}
rats <- read.csv("Rat_sightings.csv", na = c("", "NA", "N/A"))

##Removing Useless Variables 
rats <- rats %>% select(-c("Descriptor", "Complaint.Type", "Agency", "Agency.Name")) ##all those that are the same value for every row
rats <- rats %>% select(-c("Unique.Key", "Incident.Address", "Facility.Type", "Park.Facility.Name")) ##I have no idea how we would use these variables and I checked to make sure none of the Unique keys are repeated
rats <- rats %>% select(-c("Park.Borough")) ##variables that are identical to other variables (I checked)
rats <- rats %>% select(-c("Vehicle.Type", "Taxi.Company.Borough", "Taxi.Pick.Up.Location", "Bridge.Highway.Name", "Bridge.Highway.Direction", "Road.Ramp", "Bridge.Highway.Segment")) ##removing empty variables

##Cleaning with Code from Dr. Bushong
rats_clean <- rats %>%
  rename(created_date = Created.Date,
         location_type = Location.Type,
         borough = Borough) %>%
  mutate(created_date = mdy_hms(created_date)) %>%
  mutate(sighting_year = year(created_date),
         sighting_month = month(created_date),
         sighting_day = day(created_date),
         sighting_weekday = wday(created_date, label = TRUE, abbr = FALSE)) %>%
  filter(borough != "Unspecified")

##Summarizing the Data
```